spring:
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8761
      server:
        git:
          uri: file://${user.home}/config-repo
eureka:
  dashboard:
    path: /eureka-dashboard
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://$(eureka.instance.hostname):${server.port}/eureka/
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

spring:
  profiles: dev
  datasource:
    url: jdbc:psql://localhost/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop


